CREATE TABLE IF NOT EXISTS vets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT
);
CREATE INDEX ON vets (last_name);

CREATE TABLE IF NOT EXISTS specialties (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON specialties (name);

CREATE TABLE IF NOT EXISTS vet_specialties (
  vet_id       INT NOT NULL REFERENCES vets (id),
  specialty_id INT NOT NULL REFERENCES specialties (id),
  UNIQUE (vet_id, specialty_id)
);

CREATE TABLE IF NOT EXISTS types (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON types (name);

CREATE TABLE IF NOT EXISTS owners (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT,
  address    TEXT,
  city       TEXT,
  telephone  TEXT
);
CREATE INDEX ON owners (last_name);
CREATE UNIQUE INDEX uc_owner_name_telephone ON owners (LOWER(first_name), LOWER(last_name), telephone);

CREATE TABLE IF NOT EXISTS pets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT,
  birth_date DATE,
  type_id    INT NOT NULL REFERENCES types (id),
  owner_id   INT REFERENCES owners (id)
);
CREATE INDEX ON pets (name);
CREATE INDEX ON pets (owner_id);

CREATE TABLE IF NOT EXISTS visits (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INT REFERENCES pets (id),
  visit_date  DATE,
  description TEXT
);
CREATE INDEX ON visits (pet_id);

CREATE TABLE IF NOT EXISTS appointment_types (
  id                        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                      VARCHAR(80) NOT NULL,
  default_duration_minutes  INT NOT NULL,
  specialty_id              INT REFERENCES specialties (id),
  description               VARCHAR(255),
  version                   INT NOT NULL DEFAULT 0,
  CONSTRAINT uk_appointment_types_name UNIQUE (name),
  CONSTRAINT chk_appointment_type_duration CHECK (default_duration_minutes >= 1)
);
CREATE INDEX idx_appointment_types_name ON appointment_types (name);

CREATE TABLE IF NOT EXISTS appointments (
  id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version             INT NOT NULL DEFAULT 0,
  appointment_date    DATE NOT NULL,
  start_time          TIME NOT NULL,
  end_time            TIME NOT NULL,
  status              VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
  notes               VARCHAR(500),
  pet_id              INT NOT NULL REFERENCES pets (id),
  vet_id              INT NOT NULL REFERENCES vets (id),
  appointment_type_id INT NOT NULL REFERENCES appointment_types (id),
  created_at          TIMESTAMP NOT NULL,
  cancelled_at        TIMESTAMP,
  CONSTRAINT chk_appointment_time_range CHECK (start_time < end_time),
  CONSTRAINT chk_appointment_status CHECK (status IN ('SCHEDULED','CONFIRMED','CANCELLED','COMPLETED')),
  CONSTRAINT chk_appointment_version CHECK (version >= 0)
);
CREATE INDEX idx_appointment_vet_date ON appointments (vet_id, appointment_date, start_time, end_time);
CREATE INDEX idx_appointment_pet_date ON appointments (pet_id, appointment_date);
CREATE INDEX idx_appointment_status ON appointments (status);

CREATE TABLE IF NOT EXISTS clinic_schedule_config (
  id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_of_week            INT NOT NULL,
  open_time              TIME NOT NULL,
  close_time             TIME NOT NULL,
  slot_duration_minutes  INT NOT NULL DEFAULT 30,
  is_open                BOOLEAN NOT NULL DEFAULT TRUE,
  version                INT NOT NULL DEFAULT 0,
  CONSTRAINT uk_clinic_schedule_day UNIQUE (day_of_week),
  CONSTRAINT chk_clinic_schedule_day_range CHECK (day_of_week >= 1 AND day_of_week <= 7),
  CONSTRAINT chk_clinic_slot_duration_bounds CHECK (slot_duration_minutes >= 5),
  CONSTRAINT chk_clinic_open_close CHECK (is_open = FALSE OR open_time < close_time)
);

CREATE TABLE IF NOT EXISTS vet_schedules (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id       INT NOT NULL REFERENCES vets (id),
  day_of_week  INT NOT NULL,
  start_time   TIME NOT NULL,
  end_time     TIME NOT NULL,
  is_available BOOLEAN NOT NULL DEFAULT TRUE,
  version      INT NOT NULL DEFAULT 0,
  CONSTRAINT uk_vet_schedule_day UNIQUE (vet_id, day_of_week),
  CONSTRAINT chk_vet_schedule_day_range CHECK (day_of_week >= 1 AND day_of_week <= 7),
  CONSTRAINT chk_vet_schedule_time_range CHECK (start_time < end_time)
);

CREATE TABLE IF NOT EXISTS vet_time_off (
  id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id   INT NOT NULL REFERENCES vets (id),
  off_date DATE NOT NULL,
  reason   VARCHAR(255),
  version  INT NOT NULL DEFAULT 0,
  CONSTRAINT uk_vet_time_off UNIQUE (vet_id, off_date)
);
